### ISSUE TITLE
[FEATURE] Remember current series

### ISSUE THREAD

**Issue by stijndcl** [thepieterdc/dodona-plugin-jetbrains#131]
**Briefly describe the feature idea:**
Make the plugin remember your current series so you don't have to manually select it every time you make a new exercise.

**Comment by BTWS2** [comment]
@thepieterdc When I make a new Dodona exercise the plugin doesn't remember the course and series when I want to create a new exercise. Are you able to reproduce this issue?

The plugin now always selects the first course from this academic year and the last (most recent) series.
