### ISSUE TITLE
[FEATURE] Check if there is a valid API token when starting Pycharm

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-jetbrains#147]
Some students installed the plugin and generated a token on dodona.ugent.be and forget (or don't find immediately where) to enter the token. Is it possible to check if there is a valid API token when starting PyCharm with a button to enter the API key (similar to the VS Code extension)?

**Comment by thepieterdc** [comment]
If you attempt to do anything that requires a token, you will already receive a pop-up. I don't think we should be displaying these pop-ups when starting the IDE since this can be annoying and lead to issues if for example Dodona has a temporary outage.
