### ISSUE TITLE
[FEATURE] Sumbit (IntelliJ) exercises but remove packages automatically. 

### ISSUE THREAD

**Issue by tdpeuter** [thepieterdc/dodona-plugin-jetbrains#208]
**Briefly describe the feature idea:**
When submitting exercise to Dodona, execution failes because unknown packages are imported. Remove these lines by default?

**Comment by thepieterdc** [comment]
Could you provide an example of these unknown packages?

**Comment by fortemfiducia** [comment]
I feel like I should rephrase the idea: 
When working in IntelliJ, you work in packages, therefor the beginning of your .java file has `package folder.subfolder.whatever;`. This is the line that creates issues when submitting to Dodona.
