### ISSUE TITLE
[BUG] Add Dodona icon to "Main Toolbar Right" by default and show check mark icon

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-jetbrains#258]
# Description
PyCharm has a [new UI](https://www.jetbrains.com/help/pycharm/new-ui.html). Because of the new UI, the `Submit to Dodona` button is gone, but I added it back manually.

I added this button manually to the toolbar following these steps:
* Settings > Appearance & Behavior > Menus and Toolbars > Main Toolbar Right
* Select "Main Toolbar Right" > `+` - icon > Add Action...
* Search for "Submit to Dodona"
* The icon is back, but the blue check mark icon is gone.

**Is it possible to add the Dodona icon to "Main toolbar right" by default? Can you bring the blue check mark back to the icon?**

Edit: It's possible to select the icon, but you have to select it manually in a long list.
![image](https://user-images.githubusercontent.com/56451049/233572449-dc6d045d-5ce1-43ac-9ec1-2e926de87d2a.png)

# Environment
- OS: Windows 11
- IDE: PyCharm 2023.1 (new UI)
- Plugin version: 2.1.7
- Java version: Version 8 update 361

# Screenshots
![image](https://user-images.githubusercontent.com/56451049/233566361-9cd263b7-5eb2-41e8-9452-201258187d22.png)

**Comment by BTWS2** [comment]
@thepieterdc this [plugin](https://plugins.jetbrains.com/plugin/9742-live-coding-in-python) (https://github.com/donkirkby/live-py-plugin) managed to get the icons in the toolbar in the new UI.
![image](https://github.com/thepieterdc/dodona-plugin-jetbrains/assets/56451049/3dbbc738-afde-47ec-bbcd-f47c15f77a69)

**Comment by thepieterdc** [comment]
I've somehow missed this PR completely, will have a look at this tonight. Thanks a lot!
