### ISSUE TITLE
[BUG] `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-jetbrains#286]
# Description

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.github.thepieterdc.dodona.plugin.actions.SubmitAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: be.ugent.piedcler.dodona]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

# Environment
- OS: Windows 10
- IDE:
```
PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
```
- Plugin version: 2.1.10

# Screenshots
![image](https://github.com/thepieterdc/dodona-plugin-jetbrains/assets/56451049/37825747-4875-4496-abae-9f01886a6531)

**Comment by thepieterdc** [comment]
Hi @BTWS2 , can you please give some more details regarding when you get this error? I can't seem to reproduce it myself.

**Comment by BTWS2** [comment]
If I start PyCharm 2024.1 there is a red icon in the lower right hand corner. This button opens the window with internal errors. The error happens every time I start PyCharm 2024.1, even without interacting with the plugin.
![image](https://github.com/thepieterdc/dodona-plugin-jetbrains/assets/56451049/008124c8-bf20-4744-b3df-713c5e97c6ea)

**Comment by BTWS2** [comment]
@thepieterdc FYI: https://github.com/donkirkby/live-py-plugin/issues/612
