### ISSUE TITLE
Intelligent filenaming when creating a new exercise

### ISSUE THREAD

**Issue by thepieterdc** [thepieterdc/dodona-plugin-jetbrains#67]
Implement a framework to generate filenames upon creating a new exercise.

**Specifications**
- If it's a Java exercise, the framework should check the boilerplate of the exercise and figure out the classname, for example `MyClass` of that boilerplate (if it's available). The resulting filename should then be `MyClass.java`
- If it's a Python exercise, the name of the file should be based on the name of the exercise, but cleaned (e.g. replace all spaces by underscores/dashes, remove special characters, etc)

**Comment by Miningflo** [comment]
If you have a DOM-selector, this selection `document.getElementsByTagName("h2")[0].textContent` will allow for getting the name of the exercise (apperently, it is the only h2 element on the page)

**Comment by thepieterdc** [comment]
@Miningflo That's not the problem, we can already obtain the name of the exercise given its url without hacky HTML parsing :)

The problem is that I want the filenames to be somehow "clean". For example,

Consider an exercise named "My Cool Exercise". I could obviously name the file `My Cool Exercise.py` but that's not very clean, a cleaner version would be `my_cool_exercise.py`. For Java exercises, it's a bit more difficult. It could be that the name of the exercise is "Prime Numbers", but that the exercise requires you to write a class `class PrimeFinder`, the name of the file should then be `PrimeFinder.java`.

I will however look into this later today :)

**Comment by Miningflo** [comment]
> @Miningflo That's not the problem, we can already obtain the name of the exercise given its url without hacky HTML parsing :)
> 
> The problem is that I want the filenames to be somehow "clean". For example,
> 
> Consider an exercise named "My Cool Exercise". I could obviously name the file `My Cool Exercise.py` but that's not very clean, a cleaner version would be `my_cool_exercise.py`. For Java exercises, it's a bit more difficult. It could be that the name of the exercise is "Prime Numbers", but that the exercise requires you to write a class `class PrimeFinder`, the name of the file should then be `PrimeFinder.java`.
> 
> I will however look into this later today :) Someone else suggested to present the user with a dialog where that allows you to enter your own filename, that will probably be added as well.

Okay, well... hope it works out somehow, the numbers are a little confusing right now.
Thanks in advance!
