### ISSUE TITLE
Plugin not supported on windows?

### ISSUE THREAD

**Issue by DaanWet** [thepieterdc/dodona-plugin-jetbrains#71]
I am not able to create new dodona file, nor submit to dodona in Pycharm on Windows:
And I am receiving folowing error:
https://pastebin.com/baxkWRtQ

**Comment by Miningflo** [comment]
Probably has to do with the windows default /r/n line end

**Comment by thepieterdc** [comment]
Oh this is interesting, it's true that we didn't test it on Windows as neither of us is using Windows. I will install it in a virtual machine and come up with a fix :)

**Comment by Tram13** [comment]
Workaround: just paste the URL from dodona on the first line as comment. Like this:
`# https://dodona.ugent.be/nl/courses/121/series/1329/exercises/70570533/`

**Comment by thepieterdc** [comment]
Possible other fix (can anyone confirm this?):

Go to `File -> Settings`, under `Editor -> Code Style`, set `Line separator` to `Linux (\n)`.

**Comment by thepieterdc** [comment]
Possible fixed version is being tested right now.
