### ISSUE TITLE
[BUG] Plugin asks for token each time I start PyCharm

### ISSUE THREAD

**Issue by Zelzahn** [thepieterdc/dodona-plugin-jetbrains#74]
Every time when I start my PyCharm the plugin asks for a login token.

**System:**
 - OS: Arch Linux
- IDE: PyCharm 2018.3.4 (Professional Edition)
- JRE: 1.8.0_152-release-1343-b26 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

 - Plugin version: 1.3.1

**Comment by thepieterdc** [comment]
@Zelzahn is the authentication dialog filled in already when it asks you to enter a token, or is it blank?

Does it look like this:
![image](https://user-images.githubusercontent.com/6131398/53830389-9df6b400-3f82-11e9-9922-feedd9c1acd6.png)

Or like this:
![image](https://user-images.githubusercontent.com/6131398/53830416-ac44d000-3f82-11e9-8135-85663ce48ceb.png)

**Comment by Zelzahn** [comment]
It looks like the 2nd dialog box

**Comment by thepieterdc** [comment]
> It looks like the 2nd dialog box

Are you by any chance using KeePass? The only related issue I can seem to find is https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000047544-GIT-unable-to-remember-my-password

**Comment by Zelzahn** [comment]
Nope, but I did find that the database file is missing on my system, maybe this could be it?
![image](https://user-images.githubusercontent.com/2775701/53864362-8fdd7d80-3fec-11e9-9b8a-1ad945e5401c.png)

**Comment by thepieterdc** [comment]
> Nope, but I did find that the database file is missing on my system, maybe this could be it?
> ![image](https://user-images.githubusercontent.com/2775701/53864362-8fdd7d80-3fec-11e9-9b8a-1ad945e5401c.png)

@Zelzahn that's probably the reason indeed, this does not seem related to the plugin. You will probably experience the same issues when using the GitHub plugin/other plugins that safe credentials in the PasswordSafe.

Maybe this will be of help to you? https://www.reddit.com/r/archlinux/comments/8shru5/gnomekeyring_not_storing_credentials_of_intellij/

**Comment by maartenvn** [comment]
Reinstalling gnome-keyring fixed the issue of not storing the credentials.
However, I am now getting this error message:
![image](https://user-images.githubusercontent.com/6013068/53903084-0ad18300-4043-11e9-9d53-ea33a8179733.png)
