### ISSUE TITLE
[BUG] Stuck at "Configure exercise". 

### ISSUE THREAD

**Issue by maartenvn** [thepieterdc/dodona-plugin-jetbrains#80]
**Describe the bug**
When clicking the checkmark to send to Dodona, a window with "Configure exercise" appears and does not go away.

When restarting the IDE the prompt for adding the authentication token also appears, even though the token has already been configured.

**System:**
 - OS: Manjaro 18 (Linux Kernel 4.19.20-1-MANJARO)
- IDE: Pycharm (2018.3)
 - Plugin version: 1.3.1 (tried 1.3.2-SNAPSHOT as well)

**Screenshots**
![image](https://user-images.githubusercontent.com/6013068/53884517-0645a400-401c-11e9-9dc2-0790bade3b7f.png)

**Comment by thepieterdc** [comment]
I have seen this before, it's probably a race condition as it doesn't occur to me every time. I'll take a look into it later today.

**Comment by maartenvn** [comment]
Authentication token does not save in the settings as well.

**Comment by thepieterdc** [comment]
@maartenvn have you tried https://github.com/thepieterdc/dodona-plugin-jetbrains/issues/74 ?

**Comment by maartenvn** [comment]
I have fixed the token not being saved issue by reinstalling gnome-keyring.
However, I am now getting this error message:
![image](https://user-images.githubusercontent.com/6013068/53903517-3608a200-4044-11e9-9ce8-69419b3f3840.png)

**Comment by thepieterdc** [comment]
> I have fixed the token not being saved issue by reinstalling gnome-keyring.
> However, I am now getting this error message:
> ![image](https://user-images.githubusercontent.com/6013068/53903517-3608a200-4044-11e9-9ce8-69419b3f3840.png)

I will create a version that shows more logs within 5 minutes.

**Comment by thepieterdc** [comment]
@maartenvn Could you try using the snapshot version ([https://github.com/thepieterdc/dodona-plugin-jetbrains/releases/download/untagged-b89e61ac8e634197d4c2/ugent-dodona-1.3.3-SNAPSHOT.zip](https://github.com/thepieterdc/dodona-plugin-jetbrains/releases/download/untagged-b89e61ac8e634197d4c2/ugent-dodona-1.3.3-SNAPSHOT.zip) )

You can install this by going to `Plugins` and selecting the `Install plugin from disk` option.
![image](https://user-images.githubusercontent.com/6131398/53905025-cdbbbf80-4047-11e9-8da3-aabadec1885e.png)

If you get the error again, upload me your `idea.log` file, which you can find using this menu option. The folder will probably contain multiple `.log.1, .2, .3, ...` files, the one without a number appended to the end is the most recent one.
![image](https://user-images.githubusercontent.com/6131398/53905209-37d46480-4048-11e9-95eb-c63de29c6bcd.png)

**Comment by maartenvn** [comment]
> @maartenvn Could you try using the snapshot version (https://github.com/thepieterdc/dodona-plugin-jetbrains/releases/download/untagged-b89e61ac8e634197d4c2/ugent-dodona-1.3.3-SNAPSHOT.zip )
> 
> You can install this by going to `Plugins` and selecting the `Install plugin from disk` option.
> ![image](https://user-images.githubusercontent.com/6131398/53905025-cdbbbf80-4047-11e9-8da3-aabadec1885e.png)
> 
> If you get the error again, upload me your `idea.log` file, which you can find using this menu option. The folder will probably contain multiple `.log.1, .2, .3, ...` files, the one without a number appended to the end is the most recent one.
> ![image](https://user-images.githubusercontent.com/6131398/53905209-37d46480-4048-11e9-95eb-c63de29c6bcd.png)

The URL with the snapshot appears to be invalid for me:
"Not Found"

**Comment by thepieterdc** [comment]
@maartenvn that's probably a security measure by GitHub, try [https://drive.google.com/file/d/1YG9P2VAmCRovBa_LhBrfuxaah0n5vfQc/view?usp=drive_open](https://drive.google.com/file/d/1YG9P2VAmCRovBa_LhBrfuxaah0n5vfQc/view?usp=drive_open)

(Don't extract the zip file, just install it using the instructions given in the previous comment)

**Comment by maartenvn** [comment]
> @maartenvn that's probably a security measure by GitHub, try https://drive.google.com/file/d/1YG9P2VAmCRovBa_LhBrfuxaah0n5vfQc/view?usp=drive_open
> 
> (Don't extract the zip file, just install it using the instructions given in the previous comment)

This is the content of *idea.log*:
https://pastebin.com/raw/YrRT3UFN

**Comment by thepieterdc** [comment]
@maartenvn I see that you are using Java 11. I will install this later tonight and see if that's the cause.

**Comment by maartenvn** [comment]
> @maartenvn I see that you are using Java 11. I will install this later tonight and see if that's the cause.

I think that Java 11 is the cause of the issue.
JavaFX was removed from JDK 11 and is now a standalone library.
This could explain why the class "javafx/beans/value/ObservableValue" is not found.

**Comment by thepieterdc** [comment]
> JavaFX was removed from JDK 11 and is now a standalone library.

This is indeed the cause. I am fixing it right now and will send an updated plugin version to JetBrains for approval later tonight.
